
services:
  short-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "short-generator"
    ports:
      - "8501:8501"
    command: [ "bash", "scripts/run.sh" ]
    volumes: 
      - ./:/dad-joke-short-generator